/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ComponentSelector {
    }
    interface ExampleDialog {
        "closeDialog": () => Promise<void>;
        "openDialog": () => Promise<void>;
        "trigger": string | HTMLElement;
    }
    interface ExampleSlot {
    }
    interface ExampleSlotContainer {
    }
    interface MyComponent {
    }
}
declare global {
    interface HTMLComponentSelectorElement extends Components.ComponentSelector, HTMLStencilElement {
    }
    var HTMLComponentSelectorElement: {
        prototype: HTMLComponentSelectorElement;
        new (): HTMLComponentSelectorElement;
    };
    interface HTMLExampleDialogElement extends Components.ExampleDialog, HTMLStencilElement {
    }
    var HTMLExampleDialogElement: {
        prototype: HTMLExampleDialogElement;
        new (): HTMLExampleDialogElement;
    };
    interface HTMLExampleSlotElement extends Components.ExampleSlot, HTMLStencilElement {
    }
    var HTMLExampleSlotElement: {
        prototype: HTMLExampleSlotElement;
        new (): HTMLExampleSlotElement;
    };
    interface HTMLExampleSlotContainerElement extends Components.ExampleSlotContainer, HTMLStencilElement {
    }
    var HTMLExampleSlotContainerElement: {
        prototype: HTMLExampleSlotContainerElement;
        new (): HTMLExampleSlotContainerElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "component-selector": HTMLComponentSelectorElement;
        "example-dialog": HTMLExampleDialogElement;
        "example-slot": HTMLExampleSlotElement;
        "example-slot-container": HTMLExampleSlotContainerElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface ComponentSelector {
    }
    interface ExampleDialog {
        "trigger"?: string | HTMLElement;
    }
    interface ExampleSlot {
    }
    interface ExampleSlotContainer {
    }
    interface MyComponent {
    }
    interface IntrinsicElements {
        "component-selector": ComponentSelector;
        "example-dialog": ExampleDialog;
        "example-slot": ExampleSlot;
        "example-slot-container": ExampleSlotContainer;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "component-selector": LocalJSX.ComponentSelector & JSXBase.HTMLAttributes<HTMLComponentSelectorElement>;
            "example-dialog": LocalJSX.ExampleDialog & JSXBase.HTMLAttributes<HTMLExampleDialogElement>;
            "example-slot": LocalJSX.ExampleSlot & JSXBase.HTMLAttributes<HTMLExampleSlotElement>;
            "example-slot-container": LocalJSX.ExampleSlotContainer & JSXBase.HTMLAttributes<HTMLExampleSlotContainerElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
